server:
  ssl:
    bundle: "https"
  port: 8443
spring:
  ssl:
    bundle:
      jks:
        https:
          key:
            alias: "${KEY_ALIAS}"
          keystore:
            location: "${KEYSTORE_LOCATION}"
            password: "${KEYSTORE_PASSWORD}"
            type: "PKCS12"
  thymeleaf:
    cache: true